# Generated by Django 5.1.7 on 2025-03-11 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='description',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(default='Dirección no especificada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='Ciudad no especificada', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='Pais no especificado', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='filters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shop',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(default='Codigo postal no especificado', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='province',
            field=models.CharField(default='Provincia no especificada', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
