# Generated by Django 5.1.7 on 2025-03-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_description_shop_reference_shop_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_active',
        ),
    ]
