# Generated by Django 5.1.7 on 2025-03-12 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shop_address_alter_shop_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='images',
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.shop')),
            ],
        ),
    ]
