# Generated by Django 5.1.7 on 2025-03-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_shop_images_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shop',
            name='main_image_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_images', to='api.shop'),
        ),
    ]
