# Generated by Django 5.1.7 on 2025-04-24 08:59

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sellerrequestemailrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=api.fields.EncryptedEmailField(max_length=254, unique=True),
        ),
    ]
