# Generated by Django 5.1.7 on 2025-05-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_hash',
        ),
    ]
